services:
  - type: web
    name: telegram-bot-programmer
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: HUGGING_FACE_TOKEN
        sync: false
      - key: GROQ_MODEL
        value: openai/gpt-oss-20b
      - key: HUGGING_FACE_API_URL
        value: https://api-inference.huggingface.co/models/microsoft/DialoGPT-large
